[queries]
query_1 = """select trans_year, trans_month, sum (outgoing) as sum_outgoing, sum (incoming) as sum_incoming  
from public.t_c_all_tab_cat
group by trans_year, trans_month
order by trans_year, trans_month;"""


[connections.my_database]
    type="sql"
    dialect="mysql"
    username="xxx"
    password="xxx"
    host="example.com" # IP or URL
    port=3306 # Port number
    database="mydb" # Database name

[postgres]
host = "localhost"
port = "5432"
database = "Shailendra_Personal"
user = "shai"
password = "Manager"